name: Validação de Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Validar HTML (exemplo)
        run: echo "Simulação de validação do HTML..."

      - name: Validar CSS (exemplo)
        run: echo "Simulação de validação do CSS..."
